# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Sulci Labs Inc.

"""
sulci/telemetry.py — fingerprint + helpers for the legacy emit pipe (v0.5.2)
============================================================================

Naming note
-----------
There are TWO telemetry modules in this package, deliberately:

  * :mod:`sulci.sinks.telemetry` — the v0.5.0 ``EventSink`` implementation.
    Per-event, structured, used when a caller passes ``event_sink=`` to
    ``Cache(...)``. See ADR 0004.

  * :mod:`sulci.telemetry` (this module) — helpers for the simpler, legacy
    aggregation pipe in ``sulci/__init__.py`` that ``sulci.connect()``
    drives. Buffered, periodic flush, single endpoint
    (``POST /v1/telemetry``). See ADR 0010 for the privacy firewall on the
    receiving end.

The two pipes are independent. ``Cache.get/set`` calls into both when
configured — they don't share buffers and don't share state.

What lives here
---------------

  * :func:`build_fingerprint` — derive a stable, anonymous, config-aware
    deployment fingerprint from the active config and the persisted
    ``machine_id`` (see :func:`sulci.config.get_machine_id`).

  * :func:`python_version_str` — short version string for the wire payload.

  * :data:`WIRE_FIELDS` — the exact allowlist accepted by the gateway
    schema (``gateway/app/routes/telemetry.py::TelemetryEvent``). Imported
    into :mod:`sulci.__init__`'s ``_flush`` so we can't accidentally
    inflate a payload past what the gateway will accept (``extra='forbid'``
    on the receiving Pydantic model — anything extra is rejected with
    HTTP 422 and the batch is silently dropped).

What does NOT live here
-----------------------

The buffer, the flush thread, and the ``connect()`` entry point all stay
in ``sulci/__init__.py``. Moving them would change the public-import
shape (``sulci._emit``, ``sulci._flush``, ``sulci._event_buffer`` are all
patched by name in :mod:`tests.test_connect`) and would gain us nothing.
This module is helpers only.
"""
from __future__ import annotations

import hashlib
import sys
from typing import Any, Optional


# ── Wire contract ─────────────────────────────────────────────────────────────
# Exact set of fields the gateway TelemetryEvent model accepts.
# See gateway/app/routes/telemetry.py — model_config = ConfigDict(extra='forbid').
# Adding a field requires a coordinated PR on both sides.

WIRE_FIELDS = frozenset([
    "event",
    "backend",
    "hits",
    "misses",
    "avg_latency_ms",
    "sdk_version",
    "python_version",
    "fingerprint",
])


# ── Python version helper ─────────────────────────────────────────────────────

def python_version_str() -> str:
    """Return ``"3.11.6"``-style version. Capped to fit gateway's max_length=32."""
    v = sys.version_info
    return f"{v.major}.{v.minor}.{v.micro}"


# ── Fingerprint ───────────────────────────────────────────────────────────────

# Why blake2b: same family used elsewhere in the platform
# (``shared/crypto.py``), keyed digests not needed here, 12-byte digest
# yields 24 hex chars — well below the gateway's 64-char ``fingerprint``
# cap and short enough to display in dashboard tables without truncation.

_FINGERPRINT_DIGEST_BYTES = 12


def build_fingerprint(
    *,
    machine_id:      str,
    backend:         str,
    embedding_model: Optional[str] = None,
    threshold:       Optional[float] = None,
    context_window:  Optional[int]   = None,
) -> str:
    """Derive the stable per-deployment fingerprint sent to ``/v1/telemetry``.

    "Deployment" = (machine_id, backend, embedding_model, threshold,
    context_window) tuple. Two installs on the same machine using the
    same config produce the same fingerprint and dedupe to one row in
    the ``/v1/analytics/deployments`` listing.

    Anonymity: ``machine_id`` is a uuid4 generated by
    :func:`sulci.config.get_machine_id` on first run. It carries no
    derived information about the machine (no MAC, no hostname, no
    path). Reversing the fingerprint to identify a user requires
    knowing their machine_id, which never leaves the local config.

    Stability: a config change (e.g. ``backend='chroma'`` →
    ``backend='qdrant'``) intentionally produces a new fingerprint.
    The dashboard treats this as a new deployment, which matches user
    intuition ("I switched backends, I want to see both").

    Returns 24 hex chars.
    """
    parts = [
        machine_id,
        backend,
        embedding_model or "",
        # round threshold to 4dp so 0.85 vs 0.8500001 don't fragment
        f"{threshold:.4f}" if threshold is not None else "",
        str(context_window) if context_window is not None else "",
    ]
    payload = "|".join(parts).encode("utf-8")
    return hashlib.blake2b(payload, digest_size=_FINGERPRINT_DIGEST_BYTES).hexdigest()


# ── Wire-payload validator ────────────────────────────────────────────────────

def coerce_to_wire(payload: dict) -> dict:
    """Strip any field not in :data:`WIRE_FIELDS`.

    Defense-in-depth against future-us accidentally adding a field to
    ``_emit`` data that the gateway would reject. Called by ``_flush``
    just before serialization.

    ``None`` values are kept (Pydantic ``Optional[...]`` fields accept
    them); the gateway tolerates ``fingerprint=None`` and
    ``python_version=None``.
    """
    return {k: v for k, v in payload.items() if k in WIRE_FIELDS}
